name: api-ci

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (root)
        run: npm ci

      - name: Typecheck + tests (workspace @mag/api)
        run: |
          npm run -w @mag/api check
          npm run -w @mag/api test:cov

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: api/coverage/
