name: CI

on:
  push:
    branches:
      - main
      - "fix/**"
      - "feature/**"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-api:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            api/package-lock.json

      - name: Install deps (workspaces)
        run: npm ci

      - name: Prisma — validate schema (api)
        run: npx --prefix api prisma validate
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/db?schema=public

      - name: Typecheck (api)
        run: npm run -w api typecheck

      - name: ESLint (api)
        run: npm run -w api lint