name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node: [18, 20]
    # concorre por branch + versão do Node (cada matrix tem sua fila)
    concurrency:
      group: ci-api-${{ github.ref }}-${{ matrix.node }}
      cancel-in-progress: true

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: api/package-lock.json

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Vitest + coverage)
        run: npm test --silent

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage-${{ matrix.node }}
          path: api/coverage
          retention-days: 7
          overwrite: true
          if-no-files-found: ignore
