name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: api/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    name: Test (Node ${{ matrix.node }})
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: api/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm run typecheck
      - run: npm test --silent
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage-${{ matrix.node }}
          path: api/coverage
          retention-days: 7
          overwrite: true
          if-no-files-found: warn

  sca-sast:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: api/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm audit --audit-level=moderate
      - name: Run ESLint for SAST
        run: npm run lint

  merge-coverage-report:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage (Node 18)
        uses: actions/download-artifact@v4
        with:
          name: api-coverage-18.x
          path: ./coverage-ci/node18
      - name: Download coverage (Node 20)
        uses: actions/download-artifact@v4
        with:
          name: api-coverage-20.x
          path: ./coverage-ci/node20
      - name: Merge coverage JSON + gerar HTML
        run: |
          set -e
          mkdir -p coverage-ci/merge-input coverage-ci/merged coverage-ci/merged-html
          find coverage-ci -type f -name 'coverage-final.json' -print -exec cp {} coverage-ci/merge-input/ \;
          npx nyc@15.1.0 merge coverage-ci/merge-input coverage-ci/merged/coverage.json
          npx nyc@15.1.0 report --temp-dir=coverage-ci/merged --reporter=html --report-dir=coverage-ci/merged-html
      - name: Upload merged report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: merged-coverage-report
          path: coverage-ci/merged-html
          retention-days: 7
          overwrite: true
