name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  COVERAGE_THRESHOLD: 80

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: api/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18.x, 20.x]
    name: Test (Node ${{ matrix.node }})
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: api/package-lock.json
      - run: npm ci --no-audit --no-fund
      - run: npm run typecheck
      # força reporters pra gerar coverage-final.json, lcov e html
      - run: npm test --silent -- --coverage.reporter=json --coverage.reporter=html --coverage.reporter=lcov

      - name: Upload coverage (lcov)
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: api/coverage/lcov.info
          if-no-files-found: warn
          retention-days: 7
      - name: Upload coverage (html)
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: |
            api/coverage/**
            !api/coverage/lcov.info
          if-no-files-found: warn
          retention-days: 7
      nv:
        VITEST_COVERAGE: 1
