name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "api/package-lock.json"

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Vitest + coverage)
        run: npm run test

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: coverage
